services:
  - type: web
    name: video-compress
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://video-compress-jobi.onrender.com
