services:
  - type: web
    name: telegram-video-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:flask_app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://video-compress-jobi.onrender.com
